# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

services:
  dataset-discovery-service:
    container_name: dds
    image: local/dds:latest
    build:
      context: ../
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./config/.env
      - ./config/.env.secrets
    healthcheck:
      test: ["CMD", "curl", "-o", "/dev/null", "http://localhost:8080/q/health"]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans