# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
      - name: run tests
        run: mvn --batch-mode --update-snapshots verify formatter:validate
      - name: run sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=./target/jacoco-report/jacoco.xml -Dsonar.organization=genomicdatainfrastructure -Dsonar.projectKey=GenomicDataInfrastructure_gdi-userportal-dataset-discovery-service
  reuse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: fsfe/reuse-action@v5
