# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

name: Run Tests

on: push

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: sonarcloud
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@6f3fa030c4b8f77c1f554a860f593a654538fa38 # v1.5.6
        with:
          java-version: "21"
      - name: run tests
        run: mvn --batch-mode --update-snapshots verify formatter:validate
      - name: run sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=./target/jacoco-report/jacoco.xml -Dsonar.organization=genomicdatainfrastructure -Dsonar.projectKey=GenomicDataInfrastructure_gdi-userportal-dataset-discovery-service
  reuse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6
