# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.3
info:
  title: CKAN Package Search API
  version: 1.0.0
  description: API for searching CKAN packages using various criteria.
servers:
  - url: /
paths:
  /api/3/action/enhanced_package_search:
    post:
      summary: Searches for packages based on criteria
      operationId: package_search
      tags:
        - "ckan-query"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PackageSearchRequest"
      responses:
        "200":
          description: A list of packages matching the search criteria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackagesSearchResponse"
  /api/3/action/enhanced_package_show:
    get:
      summary: Retrieves a package by ID
      operationId: package_show
      tags:
        - "ckan-query"
      parameters:
        - name: id
          in: query
          description: The ID of the package to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The package with the specified ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CkanPackageShowResponse"
        "404":
          description: The package not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CkanErrorResponse"
  /dataset/{id}.{format}:
    get:
      summary: Retrieves a dataset by its ID, in the requested format
      operationId: retrieve_dataset_in_format
      tags:
        - "ckan-query"
      parameters:
        - name: id
          in: path
          description: The ID of the dataset to retrieve
          required: true
          schema:
            type: string
        - name: format
          in: path
          description: the expected format of the response
          required: true
          schema:
            type: string
            enum:
              - jsonld
              - rdf
              - ttl
        - name: Authorization
          in: header
          description: The authorization header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: The dataset in the requested format
          content:
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            text/turtle:
              schema:
                type: string
        "404":
          description: The package not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CkanErrorResponse"
components:
  schemas:
    PackageSearchRequest:
      type: object
      properties:
        q:
          type: string
          description: Solr search query
          default: "*:*"
        fq:
          type: string
          description: Filter query to apply
        sort:
          type: string
          description: Sorting of search results
          default: "score desc, metadata_modified desc"
        rows:
          type: integer
          description: Max number of rows to return
          default: 10
          minimum: 0
          maximum: 1000
        start:
          type: integer
          description: Offset in the complete result set
          default: 0
          minimum: 0
        facet.field:
          type: string
          description: Which facets to include in the response
        facet.limit:
          type: integer
          description: Maximum number of facets to return
          default: -1
    PackagesSearchResponse:
      type: object
      properties:
        help:
          type: string
        success:
          type: boolean
        result:
          $ref: "#/components/schemas/PackagesSearchResult"
    PackagesSearchResult:
      type: object
      properties:
        count:
          type: integer
        results:
          type: array
          items:
            $ref: "#/components/schemas/CkanPackage"
        search_facets:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/CkanFacet"
    CkanFacet:
      type: object
      properties:
        title:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
    CkanPackage:
      type: object
      properties:
        id:
          type: string
        identifier:
          type: string
        title:
          type: string
        name:
          type: string
        notes:
          type: string
        theme:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        tags:
          type: array
          items:
            $ref: "#/components/schemas/CkanTag"
        contact:
          type: array
          items:
            $ref: "#/components/schemas/CkanContactPoint"
        creator:
          type: array
          items:
            $ref: "#/components/schemas/CkanAgent"
        publisher:
          type: array
          items:
            $ref: "#/components/schemas/CkanAgent"
        datasetRelationships:
          type: array
          items:
            $ref: "#/components/schemas/CkanDatasetRelationEntry"
          title: Dataset Relationships
        dataDictionary:
          type: array
          items:
            $ref: "#/components/schemas/CkanDatasetDictionaryEntry"
          title: Data Dictionary
        issued:
          type: string
        modified:
          type: string
        metadata_created:
          type: string
        metadata_modified:
          type: string
        temporal_start:
          type: string
        temporal_end:
          type: string
        url:
          type: string
        language:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        has_version:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
          deprecated: true
        access_rights:
          $ref: "#/components/schemas/CkanValueLabel"
        conforms_to:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
          deprecated: true
        provenance:
          type: string
        spatial_uri:
          $ref: "#/components/schemas/CkanValueLabel"
        resources:
          type: array
          items:
            $ref: "#/components/schemas/CkanResource"
        dcat_type:
          $ref: "#/components/schemas/CkanValueLabel"

        # Bellow are properties from HealthDCAT
        publisher_note:
          type: array
          items:
            type: string
        publisher_coverage:
          type: array
          items:
            type: string
        publisher_type:
          type: array
          items:
            type: string
        hdab:
          type: array
          items:
            $ref: "#/components/schemas/CkanAgent"
        spatial_coverage:
          type: array
          description: A geographic region that is covered by the dataset.
          items:
            $ref: '#/components/schemas/CkanSpatialCoverage'
        spatial_resolution_in_meters:
          type: number
          format: float
          description: Minimum spatial separation resolvable in a dataset, measured in meters.
        temporal_coverage:
          type: array
          items:
            $ref: "#/components/schemas/CkanTimeWindow"
        temporal_resolution:
          type: string
        population_coverage:
          type: array
          items:
            type: string
        retention_period:
          type: array
          items:
            $ref: "#/components/schemas/CkanTimeWindow"
        purpose:
          type: array
          items:
            type: string
        legal_basis:
          type: array
          items:
            type: string
        applicable_legislation:
          type: array
          items:
            type: string
        health_theme:
          type: array
          items:
            type: string
        health_category:
          type: array
          items:
            type: string
        max_typical_age:
          type: integer
        min_typical_age:
          type: integer
        frequency:
          type: string
        number_of_records:
          type: integer
        number_of_unique_individuals:
          type: integer
        analytics:
          type: array
          items:
            type: string
        code_values:
          type: array
          items:
            type: string
        coding_system:
          type: array
          items:
            type: string
        alternate_identifier:
          type: array
          items:
            type: string
        version_notes:
          type: string
        qualified_relation:
          type: array
          items:
            type: object
            properties:
              relation:
                type: string
              role:
                type: string
              uri:
                type: string
        personal_data:
          type: array
          items:
            type: string
      required:
        - id
        - title
    CkanContactPoint:
      properties:
        name:
          type: string
          title: name
        email:
          type: string
          title: email
        uri:
          type: string
          title: uri
        identifier:
          type: string
          title: identifier
      required:
        - name
        - email
    CkanAgent:
      properties:
        name:
          type: string
          title: name
        email:
          type: string
          title: email
        url:
          type: string
          title: url
        uri:
          type: string
          title: uri
        type:
          type: string
          title: type
        identifier:
          type: string
          title: identifier
      required:
        - name
    CkanDatasetRelationEntry:
      properties:
        relation:
          type: string
        target:
          type: string
      required:
        - target
        - relation
    CkanDatasetDictionaryEntry:
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
      required:
        - name
        - type
        - description
    CkanResource:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        format:
          $ref: "#/components/schemas/CkanValueLabel"
        uri:
          type: string
        access_url:
          type: string
        download_url:
          type: string
        issued_date:
          type: string
        modified_date:
          type: string
        language:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
      required:
        - id
        - name
        - description
        - created
    CkanPackageShowResponse:
      type: object
      properties:
        help:
          type: string
        success:
          type: boolean
        result:
          $ref: "#/components/schemas/CkanPackage"
    CkanTag:
      type: object
      properties:
        id:
          type: string
        state:
          type: string
        display_name:
          type: string
        name:
          type: string
      required:
        - id
        - display_name
        - name
        - state
    CkanErrorResponse:
      type: object
      properties:
        help:
          type: string
        success:
          type: boolean
        error:
          type: object
          properties:
            __type:
              type: string
            message:
              type: string
    CkanValueLabel:
      properties:
        name:
          type: string
        display_name:
          type: string
        count:
          type: integer
      required:
        - name
        - display_name
    CkanTimeWindow:
      properties:
        start:
          type: string
        end:
          type: string
    CkanSpatialCoverage:
      type: object
      properties:
        uri:
          type: string
          description: URI
        text:
          type: string
          description: Label
        geom:
          type: string
          description: Geometry
        bbox:
          type: string
          description: Bounding Box
        centroid:
          type: string
          description: Centroid

