# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.3
info:
  title: CKAN Package Search API
  version: 1.0.0
  description: API for searching CKAN packages using various criteria.
servers:
  - url: /
paths:
  /api/3/action/package_search:
    get:
      summary: Searches for packages based on criteria
      operationId: package_search
      tags:
        - "ckan-query"
      parameters:
        - name: q
          in: query
          description: Solr search query
          required: false
          schema:
            type: string
            default: "*:*"
        - name: fq
          in: query
          description: Filter query to apply
          required: false
          schema:
            type: string
        - name: sort
          in: query
          description: Sorting of search results
          required: false
          schema:
            type: string
            default: "score desc, metadata_modified desc"
        - name: rows
          in: query
          description: Max number of rows to return
          required: false
          schema:
            type: integer
            default: 10
            minimum: 0
            maximum: 1000
        - name: start
          in: query
          description: Offset in the complete result set
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: facet.field
          in: query
          description: Which facets to include in the response
          required: false
          schema:
            type: string
      responses:
        "200":
          description: A list of packages matching the search criteria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackagesSearchResponse"
  /api/3/action/package_show:
    get:
      summary: Retrieves a package by ID
      operationId: package_show
      tags:
        - "ckan-query"
      parameters:
        - name: id
          in: query
          description: The ID of the package to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The package with the specified ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CkanPackage"
components:
  schemas:
    PackagesSearchResponse:
      type: object
      properties:
        count:
          type: integer
          description: The number of results found
        results:
          type: array
          items:
            $ref: "#/components/schemas/CkanPackage"
        search_facets:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/CkanFacet"
          description: Aggregated information about facet
    CkanFacet:
      type: object
      properties:
        title:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/CkanFacetItem"
    CkanFacetItem:
      type: object
      properties:
        name:
          type: string
        display_name:
          type: string
        count:
          type: integer
      required:
        - name
        - display_name
        - count
    CkanPackage:
      type: object
      properties:
        id:
          type: string
        identifier:
          type: string
        name:
          type: string
        notes:
          type: string
        theme:
          type: array
          items:
            type: string
        publisher_name:
          type: string
        organization:
          $ref: "#/components/schemas/CkanOrganization"
        metadata_created:
          type: string
          format: date-time
        metadata_modified:
          type: string
          format: date-time
        url:
          type: string
        language:
          type: array
          items:
            type: string
        contact_uri: #TODO check if there are other attributes to form value/label
          type: string
        has_version:
          type: array
          items:
            type: string
        access_rights:
          type: string
        conforms_to:
          type: array
          items:
            type: string
        provenance:
          type: string
        spatial_uri: #TODO check if there are other attributes to form value/label
          type: string
        resources:
          type: array
          items:
            $ref: "#/components/schemas/CkanResource"
      required:
        - id
        - title
    CkanOrganization:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        title:
          type: string
      required:
        - id
        - name
        - title
    CkanResource:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        format:
          type: string
        uri:
          type: string
        created:
          type: string
          format: date-time
        last_modified:
          type: string
          format: date-time
      required:
        - id
        - name
        - description
        - created
