# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.3
info:
  title: CKAN Package Search API
  version: 1.0.0
  description: API for searching CKAN packages using various criteria.
servers:
  - url: /
paths:
  /api/3/action/enhanced_package_search:
    post:
      summary: Searches for packages based on criteria
      operationId: package_search
      tags:
        - "ckan-query"
      parameters:
        - $ref: "#/components/parameters/AcceptLanguage"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PackageSearchRequest"
      responses:
        "200":
          description: A list of packages matching the search criteria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackagesSearchResponse"
  /api/3/action/enhanced_package_show:
    get:
      summary: Retrieves a package by ID
      operationId: package_show
      tags:
        - "ckan-query"
      parameters:
        - $ref: "#/components/parameters/AcceptLanguage"
        - name: id
          in: query
          description: The ID of the package to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The package with the specified ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CkanPackageShowResponse"
        "404":
          description: The package not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CkanErrorResponse"
  /dataset/{id}.{format}:
    get:
      summary: Retrieves a dataset by its ID, in the requested format
      operationId: retrieve_dataset_in_format
      tags:
        - "ckan-query"
      parameters:
        - name: id
          in: path
          description: The ID of the dataset to retrieve
          required: true
          schema:
            type: string
        - name: format
          in: path
          description: the expected format of the response
          required: true
          schema:
            type: string
            enum:
              - jsonld
              - rdf
              - ttl
        - name: Authorization
          in: header
          description: The authorization header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: The dataset in the requested format
          content:
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            text/turtle:
              schema:
                type: string
        "404":
          description: The package not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CkanErrorResponse"
components:
  parameters:
    AcceptLanguage:
      name: Accept-Language
      in: header
      description: Preferred language for the response
      required: false
      schema:
        type: string
        example: en
  schemas:
    PackageSearchRequest:
      type: object
      properties:
        q:
          type: string
          description: Solr search query
          default: "*:*"
        fq:
          type: string
          description: Filter query to apply
        sort:
          type: string
          description: Sorting of search results
          default: "score desc, metadata_modified desc"
        rows:
          type: integer
          description: Max number of rows to return
          default: 10
          minimum: 0
          maximum: 1000
        start:
          type: integer
          description: Offset in the complete result set
          default: 0
          minimum: 0
        facet.field:
          type: string
          description: Which facets to include in the response
        facet.limit:
          type: integer
          description: Maximum number of facets to return
          default: -1
    PackagesSearchResponse:
      type: object
      properties:
        help:
          type: string
        success:
          type: boolean
        result:
          $ref: "#/components/schemas/PackagesSearchResult"
    PackagesSearchResult:
      type: object
      properties:
        count:
          type: integer
        results:
          type: array
          items:
            $ref: "#/components/schemas/CkanPackage"
        search_facets:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/CkanFacet"
    CkanFacet:
      type: object
      properties:
        title:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
    CkanPackage:
      type: object
      properties:
        id:
          type: string
        identifier:
          type: string
        title:
          type: string
        name:
          type: string
        notes:
          type: string
        version:
          type: string
          description: Version number or other version designation of the dataset.
        license_id:
          type: string
          description: License identifier for the dataset.
        owner_org:
          type: string
          description: The CKAN organization the dataset belongs to.
        theme:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        tags:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        contact:
          type: array
          items:
            $ref: "#/components/schemas/CkanContactPoint"
        creator:
          type: array
          items:
            $ref: "#/components/schemas/CkanAgent"
        publisher:
          type: array
          items:
            $ref: "#/components/schemas/CkanAgent"
        datasetRelationships:
          type: array
          items:
            $ref: "#/components/schemas/CkanDatasetRelationEntry"
          title: Dataset Relationships
        dataDictionary:
          type: array
          items:
            $ref: "#/components/schemas/CkanDatasetDictionaryEntry"
          title: Data Dictionary
        issued:
          type: string
        modified:
          type: string
        metadata_created:
          type: string
        metadata_modified:
          type: string
        temporal_start:
          type: string
        temporal_end:
          type: string
        url:
          type: string
        language:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        has_version:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
          deprecated: true
        access_rights:
          $ref: "#/components/schemas/CkanValueLabel"
        conforms_to:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
          deprecated: true
        provenance:
          type: string
        spatial_uri:
          $ref: "#/components/schemas/CkanValueLabel"
        resources:
          type: array
          items:
            $ref: "#/components/schemas/CkanResource"
        dcat_type:
          $ref: "#/components/schemas/CkanValueLabel"

        # Below are properties from HealthDCAT
        publisher_note:
          type: string
          description: A note from the publisher about the dataset.
        publisher_coverage:
          type: array
          items:
            type: string
        publisher_type:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        trusted_data_holder:
          type: boolean
        hdab:
          type: array
          items:
            $ref: "#/components/schemas/CkanAgent"
        spatial_coverage:
          type: array
          description: A geographic region that is covered by the dataset.
          items:
            $ref: '#/components/schemas/CkanSpatialCoverage'
        spatial_resolution_in_meters:
          type: number
          format: float
          description: Minimum spatial separation resolvable in a dataset, measured in meters.
        temporal_resolution:
          type: string
        population_coverage:
          type: string
        retention_period:
          type: array
          items:
            $ref: "#/components/schemas/CkanTimeWindow"
        purpose:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        legal_basis:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        applicable_legislation:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        health_theme:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        health_category:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        max_typical_age:
          type: integer
        min_typical_age:
          type: integer
        number_of_records:
          type: integer
        number_of_unique_individuals:
          type: integer
        analytics:
          type: array
          items:
            type: string
        code_values:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        coding_system:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        alternate_identifier:
          type: array
          items:
            type: string
        version_notes:
          type: string
        qualified_relation:
          type: array
          items:
            type: object
            properties:
              relation:
                type: string
              role:
                $ref: "#/components/schemas/CkanValueLabel"
        personal_data:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        homepage:
          type: string
        uri:
          type: string
        documentation:
          type: array
          items:
            type: string
        frequency:
          $ref: "#/components/schemas/CkanValueLabel"
        in_series:
          type: array
          items:
            type: string
        is_referenced_by:
          type: array
          items:
            type: string
        quality_annotation:
          type: array
          items:
            type: object
            properties:
              body:
                $ref: "#/components/schemas/CkanValueLabel"
              motivated_by:
                $ref: "#/components/schemas/CkanValueLabel"
              target:
                type: string
        provenance_activity:
          type: array
          items:
            type: object
            properties:
              dct_type:
                type: string
              label:
                type: string
              seeAlso:
                type: string
              startedAtTime:
                type: string
              uri:
                type: string
              wasAssociatedWith:
                type: array
                items:
                  $ref: "#/components/schemas/CkanAgent"
        qualified_attribution:
          type: array
          items:
            type: object
            properties:
              role:
                type: object
              agent:
                type: array
                items:
                  $ref: "#/components/schemas/CkanAgent"
      required:
        - id
        - title
    CkanContactPoint:
      properties:
        name:
          type: string
          title: name
        email:
          type: string
          title: email
        uri:
          type: string
          title: uri
        url:
          type: string
          title: url
          description: URL for more information about the contact point.
        identifier:
          type: string
          title: identifier
    CkanAgent:
      properties:
        name:
          type: string
          title: name
        email:
          type: string
          title: email
        url:
          type: string
          title: url
        uri:
          type: string
          title: uri
        homepage:
          type: string
          title: homepage
          description: Homepage URL for the agent.
        type:
          $ref: "#/components/schemas/CkanValueLabel"
        identifier:
          type: string
          title: identifier
        actedOnBehalfOf:
          type: array
          description: Organization the agent acted on behalf of.
          items:
            $ref: "#/components/schemas/CkanAgent"
    CkanDatasetRelationEntry:
      properties:
        relation:
          type: string
        target:
          type: string
      required:
        - target
        - relation
    CkanDatasetDictionaryEntry:
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
      required:
        - name
        - type
        - description
    CkanResource:
      type: object
      properties:
        access_url:
          type: string
        applicable_legislation:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        size:
          type: integer
          format: int64
          minimum: 0
        hash:
          type: string
        hash_algorithm:
          $ref: "#/components/schemas/CkanValueLabel"
        compress_format:
          type: string
        description:
          type: string
        documentation:
          type: array
          items:
            type: string
        download_url:
          type: string
        format:
          $ref: "#/components/schemas/CkanValueLabel"
        language:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        license:
          $ref: "#/components/schemas/CkanValueLabel"
        conforms_to:
          type: array
          items:
            $ref: "#/components/schemas/CkanValueLabel"
        mimetype:
          type: string
        modified_date:
          type: string
        package_format:
          type: string
        issued_date:
          type: string
        retention_period:
          type: array
          items:
            $ref: "#/components/schemas/CkanTimeWindow"
        rights:
          type: string
        status:
          $ref: "#/components/schemas/CkanValueLabel"
        temporal_resolution:
          type: string
        name:
          type: string
        availability:
          type: string
        id:
          type: string
        spatial_resolution_in_meters:
          type: number
          format: float
        uri:
          type: string
        access_services:
          type: array
          items:
            type: object
            properties:
              access_rights:
                $ref: "#/components/schemas/CkanValueLabel"
              applicable_legislation:
                type: array
                items:
                  $ref: "#/components/schemas/CkanValueLabel"
              conforms_to:
                type: array
                items:
                  $ref: "#/components/schemas/CkanValueLabel"
              contact:
                type: array
                items:
                  $ref: "#/components/schemas/CkanContactPoint"
              creator:
                type: array
                items:
                  $ref: "#/components/schemas/CkanAgent"
              rights:
                type: array
                items:
                  type: string
              description:
                type: string
              endpoint_description:
                type: string
              endpoint_url:
                type: array
                items:
                  type: string
              format:
                type: array
                items:
                  $ref: "#/components/schemas/CkanValueLabel"
              identifier:
                type: string
              keyword:
                type: array
                items:
                  type: string
              landing_page:
                type: array
                items:
                  type: string
              language:
                type: array
                items:
                  $ref: "#/components/schemas/CkanValueLabel"
              license:
                $ref: "#/components/schemas/CkanValueLabel"
              modified:
                type: string
              publisher:
                type: array
                items:
                  $ref: "#/components/schemas/CkanAgent"
              serves_dataset:
                type: array
                items:
                  type: string
              theme:
                type: array
                items:
                  $ref: "#/components/schemas/CkanValueLabel"
              uri:
                type: string
              title:
                type: string
              hvd_category:
                type: array
                description: A data category defined in the High Value Dataset Implementing Regulation.
                items:
                  $ref: "#/components/schemas/CkanValueLabel"
      required:
        - id
        - name
        - description
        - created
    CkanPackageShowResponse:
      type: object
      properties:
        help:
          type: string
        success:
          type: boolean
        result:
          $ref: "#/components/schemas/CkanPackage"
    CkanErrorResponse:
      type: object
      properties:
        help:
          type: string
        success:
          type: boolean
        error:
          type: object
          properties:
            __type:
              type: string
            message:
              type: string
    CkanValueLabel:
      properties:
        name:
          type: string
        display_name:
          type: string
        count:
          type: integer
      required:
        - name
        - display_name
    CkanTimeWindow:
      properties:
        start:
          type: string
        end:
          type: string
    CkanSpatialCoverage:
      type: object
      properties:
        uri:
          $ref: "#/components/schemas/CkanValueLabel"
        text:
          type: string
          description: Label
        geom:
          type: string
          description: Geometry
        bbox:
          type: string
          description: Bounding Box
        centroid:
          type: string
          description: Centroid
