# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.3
info:
  title: Keycloak API
  version: 1.0.0
  description: This API allows to query the Keycloak identity provider
servers:
  - url: /
paths:
  /broker/{providerAlias}/token:
    get:
      summary: Retrieves tokens from the identity provider
      operationId: retrive_idp_tokens
      tags:
        - "keycloak-query"
      parameters:
        - name: providerAlias
          in: path
          description: The alias of the identity provider
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: The authorization header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of packages matching the search criteria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeycloakTokenResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeyCloakErrorResponse"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeyCloakErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeyCloakErrorResponse"
      security:
        - keycloak_auth:
            - read:token
components:
  securitySchemes:
    keycloak_auth:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        authorizationCode:
          tokenUrl: https://api.example.com/oauth2/token
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read:token: read tokens
  schemas:
    KeycloakTokenResponse:
      type: object
      properties:
        access_token:
          type: string
          title: The access token
        expires_in:
          type: integer
          title: The expiration time of the token
        refresh_expires_in:
          type: integer
          title: The expiration time of the refresh token
        token_type:
          type: string
          title: The type of the token
        id_token:
          type: string
          title: The ID token
        not-before-policy:
          type: integer
          title: The not-before policy
        scope:
          type: string
          title: The scope of the token
        accessTokenExpiration:
          type: integer
          title: The expiration time of the access token
    KeyCloakErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string
